[package]
name = "mal-rust"
version = "0.1.0"
authors = ["Mauro Balbi"]

[dependencies]
rustyline = "5.0.3"

regex = "1.3.3"
lazy_static = "1.4.0"

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"

[[bin]]
name = "step1_read_print"
path = "step1_read_print.rs"